swagger: '2.0'
info:
  version: ''
  title: ''
  description: ''
  contact:
    name: Godigi
    email: GoDigiGhana@stanbic.com.gh
    url: ''
  x-ibm-name: ''
host: $(catalog.host)
basePath: /TransactionServices/
schemes:
  - https
consumes:
  - application/xml
  - application/json
produces:
  - application/xml
  - application/json
paths:
  /branchposting/addtransaction:
    parameters: []
    post:
      parameters: []
      responses:
        '200':
          description: Successful Response
      operationId: AddTransactions
  /services/addtransaction:
    parameters: []
    post:
      parameters: []
      responses:
        '200':
          description: Successful Response
      operationId: addTransactions
  /services/echotest:
    parameters: []
    get:
      responses:
        '200':
          description: Successful Response
      operationId: webServiceEcho
  /services/gettransaction:
    parameters: []
    get:
      parameters:
        - in: query
          name: id
          required: false
          type: string
      responses:
        '200':
          description: Successful Response
      operationId: getTransaction
  /services/gettransactions:
    parameters: []
    get:
      parameters:
        - in: query
          name: startDate
          required: false
          type: string
        - in: query
          name: endDate
          required: false
          type: string
      responses:
        '200':
          description: Successful Response
      operationId: getTransactions
  /services/postagencytransaction:
    parameters: []
    post:
      parameters: []
      responses:
        '200':
          description: Successful Response
      operationId: postAgencyTransactions
definitions: ''
tags: ''
x-ibm-configuration:
  enforced: true
  testable: true
  phase: realized
  cors:
    enabled: true
  assembly:
    execute:
      - operation-switch:
          title: operation-switch
          case:
            - operations:
                - AddTransactions
              execute:
                - invoke:
                    title: invoke
                    timeout: 60
                    verb: POST
                    cache-response: no-cache
                    cache-ttl: 900
                    stop-on-error:
                      - null
                    version: 1.0.0
                    target-url: >-
                      ghuatgodigisrv1.gh.sbicdirectory.com:7102/TransactionServices/branchposting/addtransaction
            - operations:
                - addTransactions
              execute:
                - invoke:
                    title: invoke
                    timeout: 60
                    verb: POST
                    cache-response: no-cache
                    cache-ttl: 900
                    stop-on-error:
                      - null
                    version: 1.0.0
                    target-url: >-
                      ghuatgodigisrv1.gh.sbicdirectory.com:7102/TransactionServices/services/addtransaction
            - operations:
                - webServiceEcho
              execute:
                - invoke:
                    title: invoke
                    timeout: 60
                    verb: GET
                    cache-response: no-cache
                    cache-ttl: 900
                    stop-on-error:
                      - null
                    version: 1.0.0
                    target-url: >-
                      ghuatgodigisrv1.gh.sbicdirectory.com:7102/TransactionServices/services/echotest
            - operations:
                - getTransaction
              execute:
                - invoke:
                    title: invoke
                    timeout: 60
                    verb: GET
                    cache-response: no-cache
                    cache-ttl: 900
                    stop-on-error:
                      - null
                    version: 1.0.0
                    target-url: >-
                      ghuatgodigisrv1.gh.sbicdirectory.com:7102/TransactionServices/services/gettransaction
            - operations:
                - getTransactions
              execute:
                - invoke:
                    title: invoke
                    timeout: 60
                    verb: GET
                    cache-response: no-cache
                    cache-ttl: 900
                    stop-on-error:
                      - null
                    version: 1.0.0
                    target-url: >-
                      ghuatgodigisrv1.gh.sbicdirectory.com:7102/TransactionServices/services/gettransactions
            - operations:
                - postAgencyTransactions
              execute:
                - invoke:
                    title: invoke
                    timeout: 60
                    verb: POST
                    cache-response: no-cache
                    cache-ttl: 900
                    stop-on-error:
                      - null
                    version: 1.0.0
                    target-url: >-
                      ghuatgodigisrv1.gh.sbicdirectory.com:7102/TransactionServices/services/postagencytransaction
          otherwise: []
          version: 1.0.0
  catch: []
